// Concise cards for the ~12 families of English grammar mistakes that Polish
// speakers actually make (articles, prepositions, word order, tenses…), distilled
// by hand — commercial guides like Grammarly served only as a category map, the
// wording and examples are our own. Injected into the grammar-fix explanation
// prompt instead of PolishSpellingRules when the corrected text is English (#73
// follow-up). Cards are Polish — that is the explanation language — with English
// examples. The "(EN: kategoria)" marker names the card's category, for audit.
//
// ponytail: a static Swift constant, not a bundled resource — the base is small
// (a few KB) and frozen, so no Bundle.module/IO plumbing is warranted.
enum EnglishGrammarRules {
    static let block: String = """
    - przedimki a/an/the: polszczyzna nie ma przedimków, więc to najczęstszy błąd. «a/an» przed policzalnym rzeczownikiem w lp. wspomnianym po raz pierwszy lub dowolnym z klasy (I saw a dog; an — przed samogłoską w wymowie: an hour); «the» gdy obie strony wiedzą, o który konkretnie chodzi (the dog we saw yesterday), przy jedynych w swoim rodzaju (the sun) i w stopniu najwyższym (the best). Bez przedimka: rzeczowniki niepoliczalne i mnogie ogólnie (I like coffee, dogs are loyal), nazwy własne, posiłki, języki (I speak English). Policzalny rzeczownik w lp. NIE może stać sam: *I saw dog jest zawsze błędne. (EN: przedimki)
    - przyimki — kalki z polskiego: on Monday, in May, at 5 o'clock (nie *in Monday); depends on (nie *depends from — „zależy od" się nie przenosi); married to, similar to; listen to music; wait for; afraid of; good at; arrive in a city / at a place; go to work (nie *go to home — home bez to: go home); discuss something (bez about). Przyimka na końcu pytania nie trzeba unikać (What are you looking for?). (EN: przyimki)
    - szyk zdania: angielski trzyma sztywny porządek podmiot–orzeczenie–dopełnienie i nie pozwala wtrącić okolicznika między czasownik a dopełnienie: I like coffee very much (nie *I like very much coffee). Przymiotnik stoi przed rzeczownikiem, a przy kilku obowiązuje kolejność opinia–rozmiar–wiek–kolor–pochodzenie (a beautiful old Polish song). Przysłówki częstotliwości (always, often, never) przed czasownikiem głównym, ale po be: He never smokes; He is never late. W pytaniach inwersja z operatorem: Where does he live? (nie *Where he lives?). (EN: szyk)
    - Present Perfect vs Past Simple: określony punkt przeszłości (yesterday, in 2020, last week, ago) wymusza Past Simple: I saw him yesterday (nie *I have seen him yesterday). Present Perfect łączy przeszłość z teraz — since/for przy trwającym stanie (I have lived here for ten years), already/yet/just, doświadczenie bez daty (Have you ever been to London?). Polski ma jeden czas przeszły, stąd mylenie obu. (EN: czasy)
    - 3. osoba -s: w Present Simple he/she/it dostaje -s: he works, she watches. Po operatorze does wraca forma podstawowa: Does he work? / He doesn't work (nie *Does he works, *He doesn't works). Wyjątki: he can/must/should (czasowniki modalne bez -s), he has, he goes, he does. (EN: 3. osoba)
    - policzalność: advice, information, news, furniture, knowledge, luggage są niepoliczalne — bez a i bez liczby mnogiej: a piece of advice (nie *an advice, *advices). much/little + niepoliczalne (much time), many/few + policzalne (many people); w starannej normie less + niepoliczalne, fewer + policzalne (fewer mistakes). news mimo -s jest w lp.: the news is good. (EN: policzalność)
    - false friends: actually = „w rzeczywistości, właściwie" (aktualnie → currently); eventually = „ostatecznie, w końcu" (ewentualnie → possibly, alternatively); sympathetic = „współczujący" (sympatyczny → nice, likeable); fabric = „tkanina" (fabryka → factory); lecture = „wykład" (lektura → reading); rent = „czynsz/wynajmować" (renta → pension); chef = „szef kuchni" (szef → boss). Gdy poprawka podmienia takie słowo, nazwij różnicę znaczeń. (EN: false friends)
    - its/it's, their/there/they're, your/you're: apostrof oznacza skrót, nie dzierżawczość zaimka — it's = it is / it has, a dzierżawcze its bez apostrofu (the dog wagged its tail); they're = they are, there wskazuje miejsce/istnienie (there is), their jest dzierżawcze; you're = you are, your jest dzierżawcze. Dzierżawczość rzeczowników przeciwnie — z apostrofem: John's car, my parents' house. (EN: homofony)
    - przecinki: przed that nie stawia się przecinka (I know that you're right — inaczej niż polskie obowiązkowe „wiem, że"); podobnie bez przecinka przed defining relative clause (the book that I read). Przecinek po frazie wstępnej (After the meeting, we left) i wokół wtrąceń (my brother, who lives in London, …). Dwóch zdań głównych nie łączy sam przecinek (comma splice): *It was late, we went home → spójnik, średnik albo kropka. (EN: interpunkcja)
    - wielkie litery: miesiące, dni tygodnia, języki, narodowości i przymiotniki od nazw własnych pisze się wielką literą: January, Monday, English, Polish food — dokładnie odwrotnie niż po polsku (styczeń, poniedziałek, polski). Zaimek I zawsze wielką. (EN: wielkie litery)
    - okresy warunkowe: po if nie stawia się will — warunek stoi w czasie teraźniejszym: If it rains, we'll stay home (nie *If it will rain). Nierzeczywisty warunek: if + Past Simple, would w zdaniu głównym (If I had time, I would help); przeszły nierzeczywisty: if + Past Perfect + would have (If I had known, I would have called). (EN: warunki)
    - gerund vs bezokolicznik: enjoy, avoid, suggest, finish, mind, keep + -ing (I enjoy reading, nie *enjoy to read); want, decide, plan, hope, refuse + to (I decided to stay). Zmiana znaczenia: stop doing = przestać coś robić, stop to do = zatrzymać się, żeby coś zrobić; remember doing = pamiętać, że się zrobiło, remember to do = pamiętać, żeby zrobić. Po przyimku zawsze -ing (good at cooking, before leaving). (EN: gerund/bezokolicznik)
    """
}
