// Concise cards for the families of Polish mistakes that actually drive
// fix-grammar corrections: ~13 confusable-spelling cards distilled by hand from
// the RJP codification "Zasady pisowni i interpunkcji polskiej" (Warszawa 2024,
// Część I), plus style cards (pleonasms, calques, word order…) distilled from
// common usage guidance — style has no RJP codification, so those carry a
// "(styl: kategoria)" category marker instead of a section number. Injected into
// the grammar-fix explanation prompt (#73) so the model cites a real rule instead
// of inventing one. Polish — that is the explanation language. The "(RJP X.Y)"
// marker on each spelling card is the source section, for audit.
//
// ponytail: a static Swift constant, not a bundled resource — the base is small
// (a few KB) and frozen, so no Bundle.module/IO plumbing is warranted.
enum PolishSpellingRules {
    static let block: String = """
    - ó/u: «ó» piszemy, gdy w innych formach wymienia się na o, e lub a (stół→stoły, mój→moje, wiózł→wieźć), w zakończeniach -ów, -ówna, -ówka (chłopców, główka, stołówka) i na początku ósmy, ów; «ó» nigdy nie stoi na końcu wyrazu. Wiele wyrazów ma jednak «ó» HISTORYCZNE, bez żadnej wymiany — pisze się je z pamięci: córka, dopóki, góra, górzysty, król, później, próżny, róża, różnica, skóra, włókno, wójt, żółć. «u» m.in. na początku i końcu wyrazów, w przyrostkach -un, -unek, -us, -ulec oraz w formach czasowników na -ować, -uć (całuję, snuję). Wyjątki -uwka: skuwka, wsuwka, zasuwka. (RJP 2.2)
    - ą/ę a -om/-em/-on/-en: nosówki «ą», «ę» w wyrazach rodzimych (dąb, gęsty) i w czasie przeszłym przed ł, l (zaczął, zaczęła); «ę» na końcu w 1. os. lp. czasownika (idę, piszę) i w bierniku lp. rzeczowników żeńskich na -a (widzę tę igłę). Połączenia: -om w celowniku lm. (dzieciom, oknom), -em w narzędniku lp. r. męskiego (filmem, prezydentem), -on-/-en- przed -ka, -ko (sukienka, okienko). (RJP 2.3)
    - rz/ż: «rz» gdy wymienia się na r (wiara→wierzyć, doktor→doktorzy), po p, b, t, d, k, g, ch, j, w (przykład, brzeg, trzeba, drzewo, krzak, grzmot, chrzan, ujrzeć, wrzos) oraz w zakończeniach -arz, -erz, -mierz, -mistrz (piekarz, talerz). «ż» gdy wymienia się na g, dz, h, z, ź, s (może→mogę, drążek→drąg, grożę→groźny), po l, ł, n, r (branża, oranżada) i w obcych na -aż (bandaż, montaż). Wyjątki dla rz po spółgłosce: stopień wyższy/najwyższy -szy, -ejszy (lepszy, najgłośniejszy), ż po przedrostku (odżałować) oraz pszczoła, pszenica, kształt, wszystko. (RJP 3.5)
    - h/ch: «ch» gdy wymienia się na sz (suchy→susza, słuch→słyszeć), po s (schody, schować), na końcu wyrazu (dach, gmach; wyjątek: druh) i w miejscowniku lm. (o płucach). «h» gdy wymienia się na g, ż, z (wahać→waga) oraz w przedrostkach hekto-, hydro-, hiper-, homo- (hydroplan). Wielu wyrazów reguły nie obejmują — wtedy rozstrzyga słownik. (RJP 3.6)
    - przedrostki z-/s-/ś-: «z-» przed spółgłoską dźwięczną (zburzyć, zmarnieć), przed h (zhakować) i przed s, si, sz (zsiec, zszyć); «s-» przed bezdźwięczną p, f, k, t, c, cz, ch (spisać, skazać, stanieć, scharakteryzować); «ś-» przed ci (ściąć, ścisnąć). (RJP 3.7.3)
    - przedrostki bez-, nad-, ob-, od-, pod-, przed-, roz-, w-: pisze się zawsze tak samo, niezależnie od dźwięczności następnej głoski, mimo słyszalnego ubezdźwięcznienia (odpowiedź, podstawić, rozsupłać, wpakować). (RJP 3.7.2)
    - -ski/-cki/-dzki: «-ski» to domyślne zakończenie przymiotników, zwykle z uproszczeniem zbitki (Haga→haski, Prusy→pruski, szewc→szewski); «-cki» od tematów na t, c, ć, k, cz; «-dzki» od tematów na d, dz, dź (Łódź→łódzki, Grudziądz→grudziądzki). (RJP 3.8)
    - -ctwo/-dztwo: «-ctwo» od wyrazów z tematem na t, c, cz, ć, k (opat→opactwo, kozak→kozactwo, dziewica→dziewictwo); «-dztwo» od tematów na d, dz, dź (sąsiad→sąsiedztwo, wojewoda→województwo). Wyjątki: uchodźstwo, wychodźstwo. (RJP 3.9)
    - -ść/-źć (bezokoliczniki ze zbitką spółgłoska+ć): «-źć» gdy ź wymienia się na z lub ż (gryźć→gryzę, wieźć→wiozę, leźć→lezę); «-ść» w pozostałych (kraść→kradnę, nieść→niesie, pleść→plotę). Dotyczy WYŁĄCZNIE tej zbitki; zwykłe zakończenia -ać, -eć, -ić, -yć, -ąć (czekać, robić, ciąć) to samo miękkie -ć i ta reguła ich NIE rządzi. (RJP 3.12)
    - znaki diakrytyczne (ą, ć, ę, ł, ń, ó, ś, ź, ż): to ODRĘBNE litery, nie ozdoba litery podstawowej — opuszczenie znaku (c zam. ć, e zam. ę, l zam. ł, n zam. ń, s zam. ś, z zam. ż/ź, a zam. ą, o zam. ó) lub jego zbędne dodanie daje inną literę, inny dźwięk i zwykle inny wyraz, więc jest błędem. Gdy literą rządzi któraś z powyższych reguł (ó/u, ą/ę, rz/ż, h/ch, -ść/-źć), zacytuj TAMTĄ regułę; w pozostałych wypadkach poprawną formą jest po prostu litera ze znakiem diakrytycznym, bez doszukiwania się wymiany. Np. polski bezokolicznik kończy się na miękkie -ć, nie -c (czekać, robić, pisać). (RJP 1)
    - cząstka nie-: łącznie z rzeczownikami (nieprzyjaciel), przymiotnikami (także stopień wyższy i najwyższy: niedrogi, nienajdroższy), imiesłowami przymiotnikowymi (niepalący, nienapisany) i przysłówkami od przymiotników (niedaleko). Rozdzielnie przed czasownikami (nie chcę), wyrazami o znaczeniu czasownikowym (nie można, nie trzeba, nie warto), imiesłowami przysłówkowymi (nie będąc), formami na -no, -to (nie znaleziono), liczebnikami (nie trzy), zaimkami (nie każdy) i przy przeciwstawieniu (nie czarne, ale białe). (RJP 4.9)
    - cząstka -by/-bym/-byś/-byśmy/-byście: łącznie z osobowymi formami czasownika (robiłbym, zrobiliby), z formą bezosobową na -łoby (należałoby) oraz w spójnikach i partykułach (gdyby, żeby, aby, jakby, niby, oby). Rozłącznie po bezokoliczniku (skończyć by warto), po formach na -no, -to (zrobiono by), po wyrazach można, trzeba, warto, wolno, winien, powinien (można by, trzeba by) i po spójnikach (poszedłby albo by został). (RJP 4.5)
    - wielka/mała litera: wielką literą piszemy pierwszy wyraz zdania (po kropce, a także po ?, !, … kończących zdanie) oraz nazwy własne — imiona, nazwiska, nazwy geograficzne, przydomki (Adam Nowak, Wisła, Chrobry); w nazwach wielowyrazowych wszystkie wyrazy oprócz wewnętrznych spójników i przyimków. Małą literą wyrazy pospolite, nazwy dni i miesięcy oraz przymiotniki od nazw własnych (polski, warszawski). (RJP 8)
    - pleonazmy: nie dubluje się znaczenia już zawartego w wyrazie — „okres czasu" (okres JEST odcinkiem czasu → wystarczy okres albo czas), „cofać się do tyłu" (cofanie zawsze jest do tyłu), „fakt autentyczny", „w miesiącu maju" (maj jest miesiącem → w maju), „kontynuować dalej", „wzajemna współpraca". Poprawna forma to samo słowo bez dublującego dodatku. (styl: pleonazmy)
    - kalki z angielskiego: konstrukcje przeniesione żywcem z angielskiego brzmią po polsku obco — „adresować problem" (address an issue → zajmować się problemem, rozwiązywać go), „dedykowany czemuś" (dedicated → przeznaczony do, stworzony z myślą o; dedykować można książkę osobie), „iść do przodu z tematem" (move forward → kontynuować, zaczynać), „na koniec dnia" (at the end of the day → koniec końców, ostatecznie). Poprawka podmienia kalkę na rodzimy odpowiednik. (styl: kalki)
    - nominalizacje: rozdęta konstrukcja rzeczownikowa zamiast prostego czasownika osłabia zdanie — „dokonać otwarcia" → „otworzyć", „ulec poprawie" → „poprawić się", „przeprowadzić analizę" → „przeanalizować", „poddać kontroli" → „skontrolować". Czasownik niesie tę samą treść krócej i naturalniej. (styl: nominalizacje)
    - strona bierna: gdy wykonawca jest znany, strona czynna jest naturalniejsza i krótsza — „raport został przygotowany przez zespół" → „zespół przygotował raport". Bierna zostaje, gdy wykonawca jest nieznany lub nieistotny („dom zbudowano w 1900 r."). (styl: strona bierna)
    - szyk i enklityki: „się" oraz krótkie zaimki (mu, go, mi) nie stoją na końcu zdania ani na jego początku — najlepiej tuż po pierwszym akcentowanym członie: „wczoraj się spotkaliśmy", nie „spotkaliśmy wczoraj się"; „dałem mu go", nie „dałem go jemu" (długa forma jemu/tobie tylko pod akcentem lub w przeciwstawieniu). Naturalny polski szyk prowadzi od tematu (rzecz znana) do rematu (informacja nowa). (styl: szyk)
    - wata słowna: urzędowe wypełniacze zastępuje się krótką formą — „w dniu dzisiejszym" → „dziś", „na chwilę obecną" → „obecnie/teraz", „w miesiącu bieżącym" → „w tym miesiącu", „celem realizacji…" → „aby…", „z uwagi na fakt, że" → „ponieważ". Treść zostaje, słów ubywa. (styl: zwięzłość)
    """
}
